#!/bin/bash
# Ralph Loop Script - Autonomous Development Agent
# Continuously feeds prompts to Claude Code until goals are achieved

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="$SCRIPT_DIR/.ralph-state"
LOG_DIR="$STATE_DIR/logs"
SESSION_DIR="$STATE_DIR/sessions"

# Ensure directories exist
mkdir -p "$LOG_DIR" "$SESSION_DIR"

# Configuration
LOOP_DELAY=${RALPH_LOOP_DELAY:-10}  # Seconds between iterations
MAX_CONSECUTIVE_ERRORS=5
LONG_OP_POLL_DELAY=60

log() {
    local level="$1"
    shift
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$level] $*" >> "$LOG_DIR/ralph.log"
}

update_status() {
    local key="$1"
    local value="$2"
    # Use yq if available, otherwise sed
    if command -v yq &>/dev/null; then
        yq -i ".$key = $value" "$STATE_DIR/status.yaml"
    else
        sed -i.bak "s/^$key:.*/$key: $value/" "$STATE_DIR/status.yaml"
    fi
}

get_status() {
    local key="$1"
    grep "^$key:" "$STATE_DIR/status.yaml" | cut -d' ' -f2
}

check_stop_condition() {
    # Check for manual stop signal
    if [[ -f "$STATE_DIR/STOP" ]]; then
        log "INFO" "Stop signal detected. Shutting down gracefully."
        return 0
    fi

    # Check if all goals achieved
    if grep -q "NOT_STARTED\|BELOW_TARGET\|IN_PROGRESS" "$STATE_DIR/goals.yaml" 2>/dev/null; then
        return 1  # Goals not yet achieved
    fi

    log "INFO" "All goals achieved! Stopping."
    return 0
}

build_prompt() {
    cat <<'PROMPT'
You are Ralph, an autonomous AI agent. Read ralph.md for your guidance.

## Current Iteration Instructions

1. Read `.ralph-state/goals.yaml` to understand current targets
2. Read `.ralph-state/lessons-learned.yaml` for guidance from past iterations
3. Run `bd ready` to see available work
4. Select the highest priority ready ticket
5. Complete that ONE ticket thoroughly
6. Verify your work (run tests, shellcheck as appropriate)
7. Commit your changes with a clear message
8. Close the ticket with `bd close <ticket-id>`
9. Exit (the loop will restart for the next iteration)

## Important Reminders

- Read docs/specs/dev-spec.md for the full specification
- NEVER modify src/tig/ - the existing feature must not be touched
- Install tools from GitHub Releases only, not package managers
- If a download fails, skip that tool gracefully (don't fail the build)
- Test with: devcontainer features test -f devenv --skip-autogenerated -i mcr.microsoft.com/devcontainers/base:ubuntu .

Begin by reading the current state and selecting your task.
PROMPT
}

run_iteration() {
    local iteration="$1"
    local session_file="$SESSION_DIR/session_$(date '+%Y%m%d_%H%M%S')_$iteration.log"

    log "INFO" "Starting iteration $iteration"
    update_status "iteration" "$iteration"
    update_status "last_run" "\"$(date '+%Y-%m-%d %H:%M:%S')\""

    # Build and save prompt
    local prompt
    prompt=$(build_prompt)
    echo "$prompt" > "$SESSION_DIR/prompt_$iteration.md"

    # Invoke Claude Code with autonomous flags
    # Using --dangerously-skip-permissions for autonomous operation
    # IMPORTANT: Only use in isolated/sandboxed environments
    if echo "$prompt" | claude --dangerously-skip-permissions 2>&1 | tee "$session_file"; then
        log "INFO" "Iteration $iteration completed successfully"
        update_status "last_success" "\"$(date '+%Y-%m-%d %H:%M:%S')\""
        update_status "consecutive_errors" "0"
        local successes
        successes=$(get_status "consecutive_successes")
        update_status "consecutive_successes" "$((successes + 1))"
        return 0
    else
        log "ERROR" "Iteration $iteration failed"
        update_status "last_error" "\"$(date '+%Y-%m-%d %H:%M:%S')\""
        update_status "consecutive_successes" "0"
        local errors
        errors=$(get_status "consecutive_errors")
        update_status "consecutive_errors" "$((errors + 1))"

        if [[ $((errors + 1)) -ge $MAX_CONSECUTIVE_ERRORS ]]; then
            log "ERROR" "Max consecutive errors reached. Creating STOP signal."
            echo "Max consecutive errors reached at $(date)" > "$STATE_DIR/STOP"
        fi
        return 1
    fi
}

main() {
    log "INFO" "Ralph starting up"

    local iteration
    iteration=$(get_status "iteration")
    iteration=${iteration:-0}

    while true; do
        # Check stopping conditions
        if check_stop_condition; then
            log "INFO" "Ralph shutting down"
            exit 0
        fi

        # Increment and run
        iteration=$((iteration + 1))
        run_iteration "$iteration" || true

        # Wait before next iteration
        log "INFO" "Waiting $LOOP_DELAY seconds before next iteration"
        sleep "$LOOP_DELAY"
    done
}

main "$@"
